In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
dataset = pd.read_csv(url, sep='|')

In [4]:
dataset.head(3)

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067

In [5]:
dataset.shape

(943, 5)

# Discover what is the mean age per occupation

In [8]:
dataset.groupby('occupation')['age'].mean().round(2)

occupation
administrator    38.75
artist           31.39
doctor           43.57
educator         42.01
engineer         36.39
entertainment    29.22
executive        38.72
healthcare       41.56
homemaker        32.57
lawyer           36.75
librarian        40.00
marketing        37.62
none             26.56
other            34.52
programmer       33.12
retired          63.07
salesman         35.67
scientist        35.55
student          22.08
technician       33.15
writer           36.31
Name: age, dtype: float64

# Discover the Male ratio per occupation and sort it from the most to the least

In [23]:
gender_count = dataset.groupby('occupation')['gender'].value_counts().unstack()
gender_count

gender            F      M
occupation
administrator  36.0   43.0
artist         13.0   15.0
doctor          NaN    7.0
educator       26.0   69.0
engineer        2.0   65.0
entertainment   2.0   16.0
executive       3.0   29.0
healthcare     11.0    5.0
homemaker       6.0    1.0
lawyer          2.0   10.0
librarian      29.0   22.0
marketing      10.0   16.0
none            4.0    5.0
other          36.0   69.0
programmer      6.0   60.0
retired         1.0   13.0
salesman        3.0    9.0
scientist       3.0   28.0
student        60.0  136.0
technician      1.0   26.0
writer         19.0   26.0

In [25]:
gender_count['male_ratio'] = gender_count['M'] / (gender_count['M']+gender_count['F'])
gender_count.head(3)

gender            F     M  male_ratio
occupation
administrator  36.0  43.0    0.544304
artist         13.0  15.0    0.535714
doctor          NaN   7.0         NaN

In [27]:
gender_count['male_ratio'].sort_values(ascending=False)

occupation
engineer         0.970149
technician       0.962963
retired          0.928571
programmer       0.909091
executive        0.906250
scientist        0.903226
entertainment    0.888889
lawyer           0.833333
salesman         0.750000
educator         0.726316
student          0.693878
other            0.657143
marketing        0.615385
writer           0.577778
none             0.555556
administrator    0.544304
artist           0.535714
librarian        0.431373
healthcare       0.312500
homemaker        0.142857
doctor                NaN
Name: male_ratio, dtype: float64

# For each occupation, calculate the minimum and maximum ages

In [15]:
dataset.groupby('occupation')['age'].agg(['min', 'max'])

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

#  For each combination of occupation and gender, calculate the mean age

In [16]:
dataset.groupby(['occupation', 'gender'])['age'].mean()

occupation     gender
administrator  F         40.638889
               M         37.162791
artist         F         30.307692
               M         32.333333
doctor         M         43.571429
educator       F         39.115385
               M         43.101449
engineer       F         29.500000
               M         36.600000
entertainment  F         31.000000
               M         29.000000
executive      F         44.000000
               M         38.172414
healthcare     F         39.818182
               M         45.400000
homemaker      F         34.166667
               M         23.000000
lawyer         F         39.500000
               M         36.200000
librarian      F         40.000000
               M         40.000000
marketing      F         37.200000
               M         37.875000
none           F         36.500000
               M         18.600000
other          F         35.472222
               M         34.028986
programmer     F         32.166667
               M         33.216667
retired        F         70.000000
               M         62.538462
salesman       F         27.000000
               M         38.555556
scientist      F         28.333333
               M         36.321429
student        F         20.750000
               M         22.669118
technician     F         38.000000
               M         32.961538
writer         F         37.631579
               M         35.346154
Name: age, dtype: float64

# For each occupation present the percentage of women and men

In [31]:
gender_percentage = dataset.groupby('occupation')['gender'].value_counts(normalize=True).mul(100).round(2)
gender_percentage.head(5)

occupation     gender
administrator  M          54.43
               F          45.57
artist         M          53.57
               F          46.43
doctor         M         100.00
Name: proportion, dtype: float64

# Normalized value= Count of category/Total number of values

In [33]:
2/5

0.4